ALTER TABLE `Match` 
ADD COLUMN `LeagueSeasonId` VARCHAR(45) NULL DEFAULT NULL AFTER `Region`;

ALTER TABLE `LiveMatch` 
ADD COLUMN `LeagueSeasonId` VARCHAR(45) NULL DEFAULT NULL AFTER `Region`;

ALTER TABLE `Commentary` 
ADD COLUMN `EventDate` TIMESTAMP NULL AFTER `Id`;

ALTER TABLE `Timeline` 
ADD COLUMN `EventDate` TIMESTAMP NULL AFTER `ModifiedTime`;

ALTER TABLE `Lineups` 
ADD COLUMN `EventDate` TIMESTAMP NULL AFTER `ModifiedTime`;