ALTER TABLE `Odds` CHANGE COLUMN `Id` `Id` INT NULL;
ALTER TABLE `Odds` DROP PRIMARY KEY;

SET  @num := 0; UPDATE `Odds` SET `Id` = @num := (@num+1);

ALTER TABLE `Odds` 
CHANGE COLUMN `Id` `Id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY;